#src/domain/client.py
"""Client Domain Model.

This module defines the Client entity for managing customer/client information.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Self

from src.domain.exceptions import ItemValidationError
from src.domain.value_objects import Email, Address, Phone, Name


@dataclass
class Client:
    """Client entity representing a customer or client.

    Attributes:
        client_id: Unique identifier for the client
        name: Client's name (required)
        email: Client's email address (optional)
        address: Client's physical address (optional)
        phone: Client's phone number (optional)
        created_by_admin_id: ID of admin who created this client
        enabled: Whether the client is active
        date_created: When the client record was created
        is_deleted: Soft delete flag
        version: Optimistic concurrency control version
    """
    client_id: int
    name: Name
    email: Email | None
    address: Address | None
    phone: Phone | None
    created_by_admin_id: int = 0
    enabled: bool = True
    date_created: datetime = field(default_factory=datetime.now)
    is_deleted: bool = False
    version: int = 0

    @classmethod
    def create(
            cls,
            *,
            client_id: int,
            name: str,
            email: str | None = None,
            address: str | None = None,
            phone: str | None = None,
            created_by_admin_id: int = 0,
            enabled: bool = True
    ) -> Self:
        """Create a new client.

        Args:
            client_id: Unique identifier for the client
            name: Client's name (required)
            email: Client's email (optional)
            address: Client's address (optional)
            phone: Client's phone number (optional)
            created_by_admin_id: ID of admin creating the client
            enabled: Whether client is active (defaults to True)

        Returns:
            New Client instance

        Raises:
            DomainValidationError: If validation fails
            ValueError: If required fields are invalid

        Example:
            client = Client.create(
                name="John Doe",
                email="john@example.com",
                address="123 Main St",
                phone="+1234567890",
                created_by_admin_id=1
            )
        """
        # Validate admin ID (0 might mean system-generated)
        if created_by_admin_id < 0:
            raise ItemValidationError("Admin ID cannot be negative")

        # Generate client ID (in real app, this would come from database)
        # For now, we'll accept that client_id should be provided separately
        # or generated by repository

        try:
            # Create value objects
            name_obj = Name(name)
            email_obj = Email(email) if email else None
            address_obj = Address(address) if address else None
            phone_obj = Phone(phone) if phone else None

            # Note: client_id is NOT set here - it should be assigned by repository
            # We raise an error to make this explicit


            # In actual implementation, you might have:
            return cls(
                client_id=client_id,
                name=name_obj,
                email=email_obj,
                address=address_obj,
                phone=phone_obj,
                created_by_admin_id=created_by_admin_id,
                enabled=enabled
            )

        except ValueError as e:
            # Re-raise as domain exception
            raise ItemValidationError(f"Client validation failed: {e}") from e


    def disable(self) -> None:
        """Disable the client."""
        self.enabled = False
        self.version += 1

    def enable(self) -> None:
        """Enable the client."""
        self.enabled = True
        self.version += 1

    def soft_delete(self) -> None:
        """Mark client as deleted (soft delete)."""
        self.is_deleted = True
        self.version += 1

    def restore(self) -> None:
        """Restore a soft-deleted client."""
        self.is_deleted = False
        self.version += 1

    @property
    def is_active(self) -> bool:
        """Check if client is active (enabled and not deleted).

        Returns:
            True if client is active
        """
        return self.enabled and not self.is_deleted

    def update_contact_info(
            self,
            email: str | None = None,
            address: str | None = None,
            phone: str | None = None
    ) -> None:
        """Update client's contact information.

        Args:
            email: New email (None to keep current)
            address: New address (None to keep current)
            phone: New phone (None to keep current)

        Raises:
            DomainValidationError: If new values are invalid
        """
        try:
            if email is not None:
                self.email = Email(email) if email else None
            if address is not None:
                self.address = Address(address) if address else None
            if phone is not None:
                self.phone = Phone(phone) if phone else None

            self.version += 1
        except ValueError as e:
            raise ItemValidationError(f"Invalid contact info: {e}") from e

    def get_contact_summary(self) -> dict[str, str | None]:
        """Get summary of client's contact information.

        Returns:
            Dictionary with contact details
        """
        return {
            "name": str(self.name),
            "email": str(self.email) if self.email else None,
            "address": str(self.address) if self.address else None,
            "phone": str(self.phone) if self.phone else None,
        }

    def __eq__(self, other: object) -> bool:
        """Clients are equal if they have the same client_id."""
        if not isinstance(other, Client):
            return False
        return self.client_id == other.client_id

    def __hash__(self) -> int:
        """Hash based on client_id."""
        return hash(self.client_id)

    def __str__(self) -> str:
        """String representation for display."""
        return f"Client(id={self.client_id}, name={self.name})"
