#src/domain/client.py
"""Client Domain Model.

This module defines the Client entity for managing customer/client information.
"""

from dataclasses import dataclass, field
from datetime import datetime, UTC
from typing import Self

from src.domain.exceptions import ItemValidationError, DomainOperationError
from src.domain.value_objects import Email, Address, Phone, Name, Empty, Description


@dataclass(kw_only=True)
class Client:
    """Client entity representing a customer or client.

    Attributes:
        client_id: Unique identifier for the client
        name: Client's name (required)
        email: Client's email address (optional)
        address: Client's physical address (optional)
        phone: Client's phone number (optional)
        description: Client's description (optional)
        created_by_admin_id: ID of admin who created this client
        enabled: Whether the client is active
        date_created: When the client record was created
        version: Optimistic concurrency control version
    """
    client_id:int
    name: Name
    email: Email | Empty = field(default_factory=Empty)
    address: Address | Empty = field(default_factory=Empty)
    phone: Phone |Empty = field(default_factory=Empty)
    description: Description|Empty=field(default_factory=Empty)
    created_by_admin_id: int = 0
    enabled: bool = True


    date_created: datetime = field(
        default_factory=lambda: datetime.now(UTC)
    )
    version: int = 0

    def __post_init__(self):
        if self.client_id < 0:
            raise ItemValidationError("Invalid client ID")
        if not self.name.value:
            raise ItemValidationError("Invalid client name")
        if self.created_by_admin_id <= 0:
            raise ItemValidationError("Invalid created admin ID")


    @classmethod
    def create(
            cls,
            *,
            name: str,
            email: str ="",
            address: str ="",
            phone: str ="",
            description:str="",
            created_by_admin_id: int = 0,
            enabled: bool = True
    ) -> Self:
        """Create a new client.

        Args:
            name: Client's name (required)
            email: Client's email (optional)
            address: Client's address (optional)
            phone: Client's phone number (optional)
            description: Client's description (optional)
            created_by_admin_id: ID of admin creating the client
            enabled: Whether client is active (defaults to True)

        Returns:
            New Client instance

        Raises:
            DomainValidationError: If validation fails
            ValueError: If required fields are invalid

        Example:
            client = Client.create(
                name="John Doe",
                email="john@example.com",
                address="123 Main St",
                phone="+1234567890",
                description="Just text"
                created_by_admin_id=1
            )
        """


        # Generate client ID (in real app, this would come from database)
        # For now, we'll accept that client_id should be provided separately
        # or generated by repository

        try:
            # Create value objects



            # In actual implementation, you might have:
            return cls(
                client_id=0,
                name=Name(name),
                email=Email(email) if email else Empty(),
                address=Address(address) if address else Empty(),
                phone=Phone(phone) if phone else Empty(),
                description=Description(description) if description else Empty(),
                created_by_admin_id=created_by_admin_id,
                enabled=enabled
            )

        except ValueError as e:
            # Re-raise as domain exception
            raise ItemValidationError(f"Client validation failed: {e}") from e


    @classmethod
    def rehydrate(cls,
                  *,
                  client_id: int,
                  name: str,
                  email: str = "",
                  address: str = "",
                  phone: str = "",
                  description: str = "",
                  created_by_admin_id: int = 0,
                  enabled: bool = True
                  ):

        return cls(
            client_id=client_id,
            name=Name(name),
            email=Email(email) if email else Empty(),
            address=Address(address) if address else Empty(),
            phone=Phone(phone) if phone else Empty(),
            description=Description(description) if description else Empty(),
            created_by_admin_id=created_by_admin_id,
            enabled=enabled
        )

    def disable(self) -> None:
        """Disable the client."""
        self.enabled = False


    def enable(self) -> None:
        """Enable the client."""
        self.enabled = True


    def ensure_enabled(self) -> None:
        self._ensure_enabled()

    def _ensure_enabled(self) -> None:
        if not self.enabled:
            raise DomainOperationError("Client is disabled")


    def update_contact_info(
            self,
            name: str="",
            email: str="",
            address: str="",
            phone: str ="",
            description:str=""
    ) -> None:
        """Update client's contact information.

        Args:
            name: New name if not empty
            email: New email (None to keep current)
            address: New address (None to keep current)
            phone: New phone (None to keep current)
            description: New description
        Raises:
            DomainValidationError: If new values are invalid
        """
        try:
            if name:
                self.name=Name(name)
            if email is not None:
                self.email = Email(email) if email else Empty()

            if address is not None:
                self.address = Address(address) if address else Empty()
            if phone is not None:
                self.phone = Phone(phone) if phone else Empty()
            if description is not None:
                self.description = Description(description) if description else Empty()

        except ValueError as e:
            raise ItemValidationError(f"Invalid contact info: {e}") from e



    def __eq__(self, other: object) -> bool:
        """Clients are equal if they have the same client_id."""
        if not isinstance(other, Client):
            return False
        return self.client_id == other.client_id

    def __hash__(self) -> int:
        """Hash based on client_id."""
        return hash(self.client_id)

    def __str__(self) -> str:
        """String representation for display."""
        return f"Client(id={self.client_id}, name={self.name})"
