#src/domain/client.py
"""Client Domain Model.

This module defines the Client entity for managing customer/client information.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Self

from src.domain.exceptions import ItemValidationError
from src.domain.value_objects import Email, Address, Phone, Name, Empty, Description


@dataclass
class Client:
    """Client entity representing a customer or client.

    Attributes:
        client_id: Unique identifier for the client
        name: Client's name (required)
        email: Client's email address (optional)
        address: Client's physical address (optional)
        phone: Client's phone number (optional)
        description: Client's description (optional)
        created_by_admin_id: ID of admin who created this client
        enabled: Whether the client is active
        date_created: When the client record was created
        version: Optimistic concurrency control version
    """
    client_id: int
    name: Name
    email: Email | Empty = field(default_factory=Empty)
    address: Address | Empty = field(default_factory=Empty)
    phone: Phone |Empty = field(default_factory=Empty)
    description: Description|Empty=field(default_factory=Empty)
    created_by_admin_id: int = 0
    enabled: bool = True
    date_created: datetime = field(default_factory=datetime.now)
    version: int = 0

    @classmethod
    def create(
            cls,
            *,
            client_id: int,
            name: str,
            email: str ="",
            address: str ="",
            phone: str ="",
            description:str="",
            created_by_admin_id: int = 0,
            enabled: bool = True
    ) -> Self:
        """Create a new client.

        Args:
            client_id: Unique identifier for the client
            name: Client's name (required)
            email: Client's email (optional)
            address: Client's address (optional)
            phone: Client's phone number (optional)
            description: Client's description (optional)
            created_by_admin_id: ID of admin creating the client
            enabled: Whether client is active (defaults to True)

        Returns:
            New Client instance

        Raises:
            DomainValidationError: If validation fails
            ValueError: If required fields are invalid

        Example:
            client = Client.create(
                name="John Doe",
                email="john@example.com",
                address="123 Main St",
                phone="+1234567890",
                description="Just text"
                created_by_admin_id=1
            )
        """
        # Validate admin ID (0 might mean system-generated)
        if created_by_admin_id < 0:
            raise ItemValidationError("Admin ID cannot be negative")

        # Generate client ID (in real app, this would come from database)
        # For now, we'll accept that client_id should be provided separately
        # or generated by repository

        try:
            # Create value objects
            name_obj = Name(name)
            email_obj = Email(email) if email else Empty()
            address_obj = Address(address) if address else Empty()
            phone_obj = Phone(phone) if phone else Empty()
            description_obj=Description(description) if description else Empty()
            # Note: client_id is NOT set here - it should be assigned by repository
            # We raise an error to make this explicit


            # In actual implementation, you might have:
            return cls(
                client_id=client_id,
                name=name_obj,
                email=email_obj,
                address=address_obj,
                phone=phone_obj,
                description=description_obj,
                created_by_admin_id=created_by_admin_id,
                enabled=enabled
            )

        except ValueError as e:
            # Re-raise as domain exception
            raise ItemValidationError(f"Client validation failed: {e}") from e


    def disable(self) -> None:
        """Disable the client."""
        self.enabled = False


    def enable(self) -> None:
        """Enable the client."""
        self.enabled = True






    def update_contact_info(
            self,
            name: str="",
            email: str="",
            address: str="",
            phone: str ="",
            description:str=""
    ) -> None:
        """Update client's contact information.

        Args:
            name: New name if not empty
            email: New email (None to keep current)
            address: New address (None to keep current)
            phone: New phone (None to keep current)
            description: New description
        Raises:
            DomainValidationError: If new values are invalid
        """
        try:
            if name:
                self.name=Name(name)
            if email is not None:
                self.email = Email(email) if email else Empty()

            if address is not None:
                self.address = Address(address) if address else Empty()
            if phone is not None:
                self.phone = Phone(phone) if phone else Empty()
            if description is not None:
                self.description = Description(description) if description else Empty()

        except ValueError as e:
            raise ItemValidationError(f"Invalid contact info: {e}") from e

    def get_contact_summary(self) -> dict[str, str ]:
        """Get summary of client's contact information.

        Returns:
            Dictionary with contact details
        """
        return {
            "name": str(self.name),
            "email": str(self.email) if self.email else "",
            "address": str(self.address) if self.address else "",
            "phone": str(self.phone) if self.phone else "",
            "description": str(self.description) if self.description else ""
        }

    def __eq__(self, other: object) -> bool:
        """Clients are equal if they have the same client_id."""
        if not isinstance(other, Client):
            return False
        return self.client_id == other.client_id

    def __hash__(self) -> int:
        """Hash based on client_id."""
        return hash(self.client_id)

    def __str__(self) -> str:
        """String representation for display."""
        return f"Client(id={self.client_id}, name={self.name})"
